<div class="alert alert-block alert-info"> 
    <center><h1 "> Tarea 3: Cálculo Científico I - MAT2605</h1> </center>
</div>
    <!-- <b></b>     -->
    <h4 style="color:#173F8A;;text-align:right;"> Profesor: Manuel A. Sánchez<br> Ayudantes: Diego Vera, Tomás Malfetano <br></h4>

<!-- 
<div class="alert alert-block alert-success"> Use green boxes sparingly, and only for some specific purpose that the other boxes can't cover. For example, if you have a lot of related content to link to, maybe you decide to use green boxes for related links from each section of a notebook. </div>

<div class="alert alert-block alert-warning"> Use yellow boxes for examples that are not inside code cells, or use for mathematical formulas if needed. </div>

<div class="alert alert-block alert-danger"> In general, just avoid the red boxes. </div>

############# Markdown parser in Sphinx ##################

<div class="admonition note"> <p class="admonition-title">Note</p> <p>You should note that the title will be automatically capitalized.</p> </div>

<div class="admonition danger"> <p class="admonition-title">Don't try this at home</p> <p>...</p> </div>
 -->
<!-- <div class="admonition important"> <p>This is an admonition box without a title.</p> </div> -->

<div class="alert alert-block alert-success"> <b> Nombre de estudiante: </b> Rafael Ignacio Lorca Muñoz</div>

In [148]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

<div class="alert alert-block alert-info"> <b> Problema 1. Métodos iterativos (teorica)</b> </div>

a)  Para cada uno de los siguiente encuentre una matriz $A$ que satisface la condición
- El método de Jacobi converge para $A$ pero no converge el método SOR.
- El método de SOR converge para $A$ pero no converge el método de Gaus-Seidel.
- El método de SOR converge para $A$ pero no converge el método de Jacobi.
Justifique su elección apropiadamente.

b) Sean las matrices
$$
A = \begin{bmatrix} a & c & 0 \\ c & a & c \\ 0 & c & a \end{bmatrix}, \quad
B = \begin{bmatrix} 0 & b & 0 \\ b & 0 & b \\ 0 & b & 0 \end{bmatrix},
$$
- Probar que $\lim_{n\to\infty} B^n = 0$, si y sólo su $|b|<\sqrt{2}/2$.
- Dar condiciones necesarias y suficientes sobre $a,c$ reales, para la convergencia de los métodos de Jacobi y Gauss-Seidel aplicados a la resolución de $Ax = v$.

<div class="alert alert-block alert-success"> <b> Solución. </b> </div>

a) Sabemos por teorema que para cualquier método iterativo si se tiene que $\rho(T)<1$ el método converge, también se sabe que para matrices estrictamente diagonal dominantes Jacobi y Gauss-Seidel convergen, mientras que para matrices definidas positivas Gauss-Seidel y SOR tienen posibilidad de converger. Hay que igual tener en cuenta la elección del parámetro $\omega$ para el método SOR.

- $A = \begin{bmatrix} 2 & 1  \\ 1 & 2  \end{bmatrix}$ es una matriz que converge para Jacobi ya que es diagonal dominante, luego para que no converga SOR basta con elegir $\omega$ fuera del rango $(0,2)$.

- $A = \begin{bmatrix} 2 & -5 & 1 \\ 1 & 4 & 6 \\ -1 & 4 & 2 \end{bmatrix}$. Elegí una matriz $3\times 3$ que cumpliera con: 1. Tiene que ser una matriz definida positiva para que SOR tenga posibilidad de converger. 2. No tiene que ser estrictamente diagonal dominante para que así no converja para Jacobi ni Gaus-Seidel. La matriz elegida tiene subdeterminantes:
$$ \Delta_1 = 2 \quad \Delta_2 = 13 \quad \Delta_3 = 16 \quad :\Delta_i >0 $$ También, no es estrictamente diagonal dominante ya que: $$ \text{Fila}_1: 2<|-5| \quad \text{Fila}_2: 4<6 \quad \text{Fila}_3: 2<4 \quad $$

Se codifica a continuación el cálculo de las matrices de iteración de los métodos trabajados, se puede observar que para $\omega=0.4$ SOR converge ya que $\rho(T_{SOR}) < 1 $, mientras que los otros radios espectrales son mayores a 1.

In [93]:
def probar_matriz(A, omega = 1.0, method = 'Jacobi'):
    D = np.diag(np.diag(A))
    L = np.tril(A, -1)  
    U = np.triu(A, 1)   

    if method == 'Jacobi':
        # T_J = -D^-1 (L+U)
        TJ = -np.linalg.inv(D) @ (L + U)
        rho = max(abs(np.linalg.eigvals(TJ)))
        return rho
    
    elif method == 'Gauss-Seidel':
        # T_GS = -(D + L)^-1 U
        TGS = -np.linalg.inv(D + L) @ U
        rho = max(abs(np.linalg.eigvals(TGS)))
        return rho
    
    elif method == 'SOR':
        # SOR = (omega*L + D)^-1 * ((1-omega)*D - omega*U)
        T_SOR = np.linalg.inv(omega*L + D) @ ((1-omega)*D - omega*U)
        rho = max(abs(np.linalg.eigvals(T_SOR)))
        return rho

A = np.array([[2, 1],
              [1, 2]])

print("rho Jacobi:", probar_matriz(A, method='Jacobi'))
print("rho Gauss-Seidel:", probar_matriz(A, method='Gauss-Seidel'))
print("rho SOR:", probar_matriz(A, omega=2, method='SOR'))

print(' ')

A = np.array([[2, -5, 1],
              [1, 4, 6],
              [-1, 4, 2]])

print("rho Jacobi:", probar_matriz(A, method='Jacobi'))
print("rho Gauss-Seidel:", probar_matriz(A, method='Gauss-Seidel'))
print("rho SOR:", probar_matriz(A, omega=0.4, method='SOR'))

rho Jacobi: 0.5000000000000001
rho Gauss-Seidel: 0.25
rho SOR: 1.0

rho Jacobi: 1.8153681369762704
rho Gauss-Seidel: 1.369306393762915
rho SOR: 0.99353209064186

b.i) Nos interesa mostrar que la matriz $B$ es nilpotente, del curso de EDO recordamos que una matriz es nilpotente si todos sus valores propios son 0. Esto es porque la matriz B tiene diagonalización $B = PDP^{-1}$, entonces: $B^k = PD^kP^{-1}$ y elevar la matriz diagonal $D$ a la k es simplemente elevar los valores propios a la k. Concluimos que como:
$$ D^k = \begin{bmatrix} \lambda^k & 0 & 0  \\ 0 & \lambda^k & 0 \\  0 & 0 &\lambda^k  \end{bmatrix} \to  0 \quad ; \quad \lambda^k \to 0 \iff |\lambda| < 1 $$

Calculando los valores propios de B se obtiene el polinomio característico:$$ -\lambda^3 +2b^2\lambda = 0 \leftrightarrow \lambda_1 = 0 , \lambda_{2,3}=\pm \sqrt{2b^2} $$ 
Luego $$ |\lambda_{2,3}| < 1 \ , \ |\sqrt{2b^2}| <1 \ , \ |b|<\frac{\sqrt{2}}{2}$$

b.ii) Sabemos por teorema que los métodos de Jacobi y Gaus-Seidel convergen para matrices estrictamente diagonal dominantes. Luego un criterio suficiente para la convergencia es que: $$|a| > 2|b|$$ Calculando los radios espectrales de las matrices de iteración para $A$: $$\rho(A_{J}) = \sqrt 2 |\frac{c}{a}| \quad , \quad \rho(A_{GS}) = 2\frac{c^2}{a^2}$$
Obtenemos las condiciones: $|\frac{c}{a}| < \frac{\sqrt 2}{2} \quad , \quad c^2<\frac{a^2}{2} $.

<div class="alert alert-block alert-info"> <b> Problema 2. Métodos iterativos (práctica)</b> </div>

Sea $A\in \mathbb R^{n\times n}$ dada por
\begin{equation*}
A = 
\begin{pmatrix}
2 & -1 & 0 & \ldots & 0 \\
-1& 2 & -1 &\ddots & \vdots\\
0 & \ddots & \ddots & \ddots & 0\\
\vdots & \ddots & -1 &2& -1 \\
0 & \ldots & 0 & -1 & 2
\end{pmatrix}
\end{equation*}
y la matriz de Hilbert  $H_n\in \mathbb R^{n\times n}$ definida por 
$$
(H_{n})_{i,j} = \frac{1}{i+j-1}, \qquad \text{para } i,j=1,...,n. 
$$

Programe los métodos iterativos de Jacobi, Gauss-Seidel y SOR y calcule para $n=10$ la solución de los sistemas lineales con $b = (1,...,1)^T\in \mathbb R^{10}$, e iniciando con $x^{(0)} = b$.
Dada la tolerancia $10^{-12}$ registre en un tabla el número de iteraciones de cada uno de los métodos. Comente sus resultados.

<div class="alert alert-block alert-success"> <b> Solución. </b> </div>

In [184]:
def jacobi(A, b, x0, max_iteracion = 100, tol = 1e-12):
    x = x0.copy()
    D = np.diag(np.diag(A))
    L = np.tril(A, -1)
    U = np.triu(A, 1)
    T_J = -np.linalg.inv(D) @ (L+U)
    C_J = np.linalg.inv(D).dot(b)
    errores = []

    for i in range(max_iteracion):
        error = np.linalg.norm(b - np.dot(A, x))
        errores.append(error)

        if error < tol:
            print(f"Convergencia alcanzada en {i+1} iteraciones.")
            return x, errores
        x = T_J.dot(x) + C_J
    
    print(f'   {i+1}   |   {error}   ')
    print('Máximo de iteraciones alcanzado\n')
    return x, errores

def gauss_seidel(A, b, x0, max_iteracion = 100, tol = 1e-12):
    x = x0.copy()
    n = x.size
    D = np.diag(np.diag(A))
    L = np.tril(A)
    U = np.triu(A)
    T_GS = -np.linalg.inv(D + L) @ U
    C_GS = np.linalg.inv(D+L) @ (b)
    errores = []

    for i in range(max_iteracion):
        error = np.linalg.norm(b - np.dot(A, x))
        errores.append(error)

        if error < tol:
            print(f"Convergencia alcanzada en {i+1} iteraciones.")
            return x, errores
        x = T_GS.dot(x) + C_GS

    print(f'   {i+1}   |   {error}   ')
    print('Máximo de iteraciones alcanzado\n')
    return x, errores

def sor(A, b, x0, w = 1.5, max_iteracion = 100, tol = 1e-12):
    x = x0.copy()
    n = x.size
    D = np.diag(np.diag(A))
    L = np.tril(A)
    U = np.triu(A)
    T_SOR = np.linalg.inv(w*L+D) @ ((1-w)*D-w*U)
    C_SOR = np.linalg.solve(D+w*L,w*b)
    errores = []

    for i in range(max_iteracion):
        error = np.linalg.norm(b - np.dot(A,x))
        errores.append(error)
        if error < tol:
            print(f"Convergencia alcanzada en {i+1} iteraciones.")
            return x, errores
        x = T_SOR.dot(x) + C_SOR

    print(f'   {i+1}   |   {error}   ')
    print('Máximo de iteraciones alcanzado\n')
    return x, errores

In [185]:
def make_hilbert(n):
    hilbert = np.ones((n,n))
    for i in range(1, n):
        for j in range(1, n):
            a = 1 / (i+j-1)
            hilbert[i][j] = a
    return hilbert

def make_tridiagonal(n):
    trid = np.zeros((n,n))
    for i in range(n):
        for j in range(n):
            if i == j:
                trid[i][j] = 2
            elif j == (i+1) or j == (i-1):
                trid[i][j] = -1
    return trid

n = 10
x0 = np.ones(n)
H = make_hilbert(n)
A = make_tridiagonal(n)

# Jacobi
sol_jacobia, eja = jacobi(A, x0, x0)
sol_jacobih = jacobi(H, x0, x0)
# Gauss-Seidel
sol_seidela, ejg = gauss_seidel(A, x0, x0)
sol_seidelh = gauss_seidel(H, x0, x0)
# SOR
sol_sora = sor(A, x0, x0)
sol_sorh = sor(H, x0, x0)

   100   |   0.04545401745086548
Máximo de iteraciones alcanzado

   100   |   9.252186309835098e+110
Máximo de iteraciones alcanzado

   100   |   3.038459008095917
Máximo de iteraciones alcanzado

   100   |   4.8444847671334764e+73
Máximo de iteraciones alcanzado

   100   |   3.03845900797759
Máximo de iteraciones alcanzado

   100   |   2.999036312820899e+81
Máximo de iteraciones alcanzado

In [186]:
df_A = pd.DataFrame({'Iteracion k': np.arange(100), 'Error Jacobi': eja, 'Error GS': ejg, 'Error SOR': sol_sora[1]})
df_A

    Iteracion k  Error Jacobi  Error GS  Error SOR
0             0      2.828427  2.828427   2.828427
1             1      2.645751  3.288237   3.530928
2             2      2.524876  3.014736   3.068366
3             3      2.417385  3.083387   3.463116
4             4      2.316719  3.037696   3.203014
..          ...           ...       ...        ...
95           95      0.053630  3.038459   3.038459
96           96      0.051457  3.038459   3.038459
97           97      0.049373  3.038459   3.038459
98           98      0.047373  3.038459   3.038459
99           99      0.045454  3.038459   3.038459

[100 rows x 4 columns]

In [187]:
df_H = pd.DataFrame({'Iteracion k': np.arange(100), 'Error J': sol_jacobih[1], 'Error GS': sol_seidelh[1], 'Error SOR': sol_sorh[1]})
df_H

    Iteracion k        Error J      Error GS     Error SOR
0             0   1.003406e+01  1.003406e+01  1.003406e+01
1             1   9.749206e+01  6.113356e+01  7.555558e+01
2             2   1.456388e+03  3.422866e+02  5.038927e+02
3             3   1.751744e+04  1.864633e+03  3.283757e+03
4             4   2.349627e+05  1.010564e+04  2.131832e+04
..          ...            ...           ...           ...
95           95  3.310584e+106  5.640643e+70  1.692924e+78
96           96  4.280451e+107  3.053574e+71  1.098306e+79
97           97  5.534450e+108  1.653058e+72  7.125405e+79
98           98  7.155820e+109  8.948863e+72  4.622699e+80
99           99  9.252186e+110  4.844485e+73  2.999036e+81

[100 rows x 4 columns]

Con estos resultados se puede apreciar que la matriz tridiagonal está mucho mejor condicionada que la matriz de Hilbert, los errores en la última se disparan, llegando al orden de $10^{73}$ en el método de Gauss-Seidel (que fue el menor). Para el valor de $\omega = 1.5$ se puede apreciar que el método de SOR se parece bastante a Gauss-Seidel, se observa de forma clara en la primera tabla ya que los errores son bastante similares. Para la tolerancia pedida, ningún método converge, sin embargo se puede apreciar que Jacobi para la matriz A se acerca bastante y muestra signos de convergencia.

<div class="alert alert-block alert-info"> <b> Problema 3. Iteracion de potencia, inversa y cociente de Rayleigh (teorico)</b> </div>

Suponga que una matriz diagonalizable que tiene un par $\lambda_1, \lambda_2$ de valores propios dominantes con signo opuesto, esto es, $\lambda_1=-\lambda_2$, y $|\lambda_1|>|\lambda_i|$, para $i>2$. 
Explique como se puede obtener una aproximación usando la iteración de potencia a los dos vectores propios correspondientes.

<div class="alert alert-block alert-success"> <b> Solución. </b> </div>

Lo que hacemos en el método de la potencia es escribir un vector x en función de vectores propios, luego al multiplicar varias veces por la matriz $A$ queda lo siguiente: $$ Ax = \sum\limits^n_{j=1}\beta_j Av^{(j)} = \sum\limits^n_{j=1}\beta_j \lambda_jv^{(j)} $$
$$ A^kx = \sum\limits^n_{j=1}\beta_j \lambda_j^k v^{(j)}$$

Normalmente se factoriza por $\lambda_1^k$ (dominante), entonces todos los términos $(\frac{\lambda_i}{\lambda_1})^k \to 0$. Sin embargo En este caso al hacer este paso quedaría:
$$ A^kx = \lambda_i^k\sum\limits^n_{j=1}\beta_j (\lambda_j/\lambda_1)^k v^{(j)} \sim \lambda_1^k\beta_1v^{(1)}\pm\lambda_1^k\beta_2v^{(2)}$$
Esto ya que $(\lambda_2/\lambda_1)^k = -1^k$. 

La iteración inversa es un método muy parecido el método al de la potencia ya que también se multiplica una matriz por un vector de forma iterada, sin embargo, se multiplica por $A^{-1}$. Si tomamos la matriz $A^{-1} = (A-\mu I)$, entonces el método converge a los valores propios $(\lambda_i -\mu)^{-1}$ con $\lambda_i$ los valores propios de A. Si nos fijamos, el valor propio dominante del método inverso es el menor valor propio de $A$ desplazado $\mu$. Luego, si queremos converger a $\lambda_2$ se puede usar $\mu$ negativo o simplemente un valor cercano a $\lambda_2$.

<div class="alert alert-block alert-info"> <b> Problema 4. Iteracion de potencia, inversa y cuociente de Rayleigh (practico)</b> </div>

Considere la matriz 
\begin{equation}
A(\alpha) = 
\begin{pmatrix}
\alpha & 2 & 3 & 13\\
5 & 11 & 10 & 8 \\
9 & 7 & 6 & 12 \\
4 & 14 & 15 & 1
\end{pmatrix}
\end{equation}
para $\alpha \in \mathbb R$. Calcule, para $\alpha = 30$ y $\alpha = -30$, los valores propios con  mayor y menor modulo utilizando:

- El método de la potencia con vector inicial $(1,1,1,1)^T$ y la iteración inversa con $\mu$ el centro del círculo de Gershgorin correspondiente.
- El método de la potencia con cociente de Rayleigh.

Registre el número de iteraciones en ambos casos y compárelos. Comente sus resultados.

<div class="alert alert-block alert-success"> <b> Solución. </b> </div>

Para calcular el valor propio dominante de $A$, se toma el $\mu =$ centro del círculo de Gershgorin con mayor valor absoluto, así el método converge a $\frac{1}{\lambda_n}$, $\lambda_n$ siendo el dominante. Si utilizamos el $\mu$ con menor valor absoluto, el método converge a el menor valor propio de $A$, se puede simplemente utilizar también $\mu = 0$.

In [225]:
def discos_de_Gershgorin(A):
    n = A[0].size
    discos = dict() # centro: radio
    for i in range(n):
        r = 0
        for j in range(n):
            if i != j:
                r += abs(A[i][j])
        centro = A[i][i]
        discos[centro] = r
    return discos

def iteracion_inversa(A, x0, calcular, max_iter = 100, tol = 1e-12):
    x = x0.copy()
    discos = discos_de_Gershgorin(A)
    # Aproximaciones de los valores propios mayor y menor:
    centros = np.array(list(discos.keys())) ; radios = np.array(list(discos.values()))
    mu = np.max(centros + radios) ; nu = np.min(centros - radios)
    p = np.argmax(np.abs(x))
    lambdas = [] ; xlist = []

    # Iteración 
    for i in range(max_iter):
        if calcular == 'max':
            y = np.linalg.solve(A - mu * np.eye(A.shape[0]), x)       
            x = y/np.linalg.norm(y)
            delta = y[p] 
            lam = mu + 1.0/delta
            lambdas.append(lam)

        elif calcular == 'min':
            y = np.linalg.solve(A - nu * np.eye(A.shape[0]), x)
            x = y/np.linalg.norm(y)
            delta = y[p] 
            lam = nu + 1.0/delta
            lambdas.append(lam)

        if i > 0 and abs(lambdas[-1] - lambdas[-2]) < tol:
            print('--------------------------------')
            print('Convergencia en iteración:', i+1)
            print('Valor estimado:', lam)
            print('--------------------------------')
            return lam, xlist, i+1

        xlist.append(x)
        p = np.argmax(np.abs(y)) 
        x = y/y[p]

    print('Máximo de iteración alcanzado ...')
    print(f'Valor propio estimado en iteración {i+1}:\n {lam}')

    return lam, xlist, max_iter

In [220]:
def iteracion_rayleigh(A, x0, max_iter = 100, tol = 1e-12):
    x = x0.copy()
    # r = x.dot(A.dot(x))/(x.dot(x)) Cociente de Rayleigh
    lambdas=[]; xlist=[]

    for i in range(max_iter):
        y = A.dot(x)
        x = y / np.linalg.norm(y, ord = 2)
        lam = x.dot(A.dot(x))/(x.dot(x))
        lambdas.append(lam) ; xlist.append(x)
        
        if i > 0 and abs(lambdas[-1] - lambdas[-2]) < tol:
            print('--------------------------------')
            print('Convergencia en iteración:', i+1)
            print('Valor estimado:', lam)
            print('--------------------------------')
            return lambdas[-1], xlist, i+1

    print('Máximo de iteración alcanzado ...')
    print(f'Valor propio estimado en iteración {i+1}:\n {lambdas[-1]}')

    return lambdas[-1] , xlist, max_iter

In [226]:
x0 = np.ones(4)
A1 = np.array([[30 , 2 , 3 , 13], 
               [5 , 11 , 10 , 8 ], 
               [9 , 7 , 6 , 12],
               [4 , 14 , 15 , 1]])
A2 = np.array([[-30 , 2 , 3 , 13], 
               [5 , 11 , 10 , 8 ], 
               [9 , 7 , 6 , 12],
               [4 , 14 , 15 , 1]])

r1 = iteracion_inversa(A1, x0, 'max')
print(' ')

r2 = iteracion_inversa(A1, x0, 'min')
print(' ')

r3 = iteracion_inversa(A2, x0, 'max')
print(' ')

r4 = iteracion_inversa(A2, x0, 'min')
print(' ')

--------------------------------
Convergencia en iteración: 25
Valor estimado: 39.396010862253206
--------------------------------

--------------------------------
Convergencia en iteración: 77
Valor estimado: -9.502213682718718
--------------------------------

--------------------------------
Convergencia en iteración: 14
Valor estimado: 29.735874631637284
--------------------------------

--------------------------------
Convergencia en iteración: 39
Valor estimado: -30.643027058224035
--------------------------------

In [227]:
df = pd.DataFrame({'Método': ['Iteración Inversa']*4,
                    'Valor Propio': [max(np.linalg.eigvals(A1)),min(np.linalg.eigvals(A1)),max(np.linalg.eigvals(A2)),min(np.linalg.eigvals(A2))],
                      'Estimación': [r1[0], r2[0], r3[0], r4[0]], 'Iteraciones': [r1[2], r2[2], r3[2], r4[2]]})
df

              Método  Valor Propio  Estimación  Iteraciones
0  Iteración Inversa     39.396011   39.396011           25
1  Iteración Inversa     -9.502214   -9.502214           77
2  Iteración Inversa     29.735875   29.735875           14
3  Iteración Inversa    -30.643027  -30.643027           39

In [228]:
r1 = iteracion_rayleigh(A1, x0)
print(' ')

r2 = iteracion_rayleigh(A2, x0)
print(' ')

--------------------------------
Convergencia en iteración: 32
Valor estimado: 39.396010862253654
--------------------------------

Máximo de iteración alcanzado ...
Valor propio estimado en iteración 100:
 -29.6211563017545

In [229]:
df = pd.DataFrame({'Método': ['Potencia con Rayleigh']*2,
                    'Valor Propio': [max(np.linalg.eigvals(A1)),max(np.linalg.eigvals(A2))],
                      'Estimación': [r1[0], r2[0]], 'Iteraciones': [r1[2], r2[2]]})
df

                  Método  Valor Propio  Estimación  Iteraciones
0  Potencia con Rayleigh     39.396011   39.396011           32
1  Potencia con Rayleigh     29.735875  -29.621156          100

Podemos ver que para todas las iteraciones los métodos programados convergen menos para la última, sin embargo converge a un valor cercano pero con el signo opuesto. A simple vista igualmente parece ser que ambos funcionan, eso sí, comparativamente me quedo con el método de la potencia inversa ya que puede calcular otros valores propios que no sean el dominante de la matriz. Esto sumado a que converge más rápido que el de la Potencia con Rayleigh. Esto muestra que para $\mu \approx \lambda$, el método de potencia inverso puede llegar a ser más rápido que el de la potencia con coeficiente de Rayleigh. 

Finalmente, sobre las matrices: $A_1$ con $\alpha = 30$ convergió comparativamente más lento que $A_2$ con $\alpha = -30$ en el método de iteración inversa. Esto también tiene reespaldo de la teoría ya que como mencioné anteriormente, el método inverso converge al autovalor mayor, luego la razón de convergencia del método es de $$ \frac{\lambda_j - \mu}{\lambda_i - \mu} $$

Luego como $\mu \approx \lambda_j$, la fracción es muy pequeña, por lo que el método converge rápido. Mientras mejor sea la aproximación, mejor la convergencia.